"""empty message

Revision ID: 1.2.0
Revises: 1.1.0
Create Date: 2024-12-21 18:15:25.951089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1.2.0'
down_revision = '1.1.0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_info_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=14, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_info_id', 'currency', name='_month_currency_uc')
    )
    # op.add_column('transaction', sa.Column('currency', sa.String(length=3), nullable=True))
    # op.execute('UPDATE `transaction` SET currency = "USD"')
    # op.alter_column('transaction', 'currency', nullable=False)
    op.execute('ALTER TABLE `transaction` ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT "USD"')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'currency')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
