"""add currencies and exchange rates

Revision ID: 1.2.0
Revises: 1.1.0
Create Date: 2024-12-31 12:02:12.071612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1.2.0'
down_revision = '1.1.0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_info_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['month_info_id'], ['month_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_info_id', 'currency', name='_month_currency_uc')
    )

    op.execute('ALTER TABLE `asset_account` ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT "USD"')
    op.execute('ALTER TABLE `investment_income` ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT "USD"')
    op.execute('ALTER TABLE `transaction` ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT "USD"')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'currency')
    op.drop_column('investment_income', 'currency')
    op.drop_column('asset_account', 'currency')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
